language: csharp
mono: none
solution: EFCore-Adapter.sln
dist: xenial
dotnet: 
    - 3.1

env: 
    global:
        - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
        - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
        - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
        - DOTNET_CLI_TELEMETRY_OPTOUT=true
        - BUILD_CONFIGURATION=Release

install:
    - sudo apt-get update
    - sudo apt-get install apt-transport-https
    - sudo apt-get update
    - sudo apt-get install dotnet-runtime-2.1 -y

script:
    - echo $BUILD_CONFIGURATION
    - dotnet build -c $BUILD_CONFIGURATION
    - sudo dotnet tool install coveralls.net --tool-path "./tools"
    - dotnet test -c $BUILD_CONFIGURATION /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_BRANCH
    - echo $REPO_COMMIT_AUTHOR
    - echo $REPO_COMMIT_AUTHOR_EMAIL
    - echo $REPO_COMMIT_MESSAGE
    - echo $TRAVIS_JOB_ID
    - echo $TRAVIS_PULL_REQUEST_SLUG
    - echo $TRAVIS_REPO_SLUG
    - 'if [[ $TRAVIS_PULL_REQUEST_SLUG = $TRAVIS_REPO_SLUG ]]; then ./tools/csmacnz.Coveralls --opencover -i coverage.opencover.xml --repoToken $COVERALLS_REPO_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName travis-ci  --useRelativePaths; fi'

deploy:
  provider: script
  script: dotnet pack -c $BUILD_CONFIGURATION && dotnet nuget push EFCore-Adapter/bin/Debug/Casbin.NET.Adapter.EFCore.*.nupkg -k $TRAVIS_CASBIN_NUGET_KEY -s https://api.nuget.org/v3/index.json
  on:
    tags: true
    branch: master

